export default {
  EXECUTE: 'EXECUTE',
  DELAY_EXECUTION: 'DELEGATE_EXECUTION',
  PAUSE_EXECUTION: 'PAUSE_EXECUTION',
  RESUME_EXECUTION: 'RESUME_EXECUTION',
  CANCEL_EXECUTION: 'CANCEL_EXECUTION',
}
